include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_relative_imports
    - avoid_dynamic_calls
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - empty_statements
    - flutter_style_todos
    - no_duplicate_case_values
    - discarded_futures
    - comment_references
    - unnecessary_statements
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_void_async
    - combinators_ordering
    - join_return_with_assignment
    - package_api_docs
    - prefer_single_quotes
